- name: Copy mongodb repo file to destination 
  ansible.builtin.copy:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongodb.repo

- name: Installing mongodb
  ansible.builtin.yum:
    name: mongodb-org
    state: installed

- name: Update MongoDB Config
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0' 

- name: Starting MongoDB 
  ansible.builtin.service:
    name: mongod 
    state: started
    enabled: yes

- name: Download and extract mongodb 
  ansible.builtin.unarchive:
    src: https://github.com/stans-robot-project/mongodb/archive/main.zip
    dest: /tmp 
    remote_src: yes  # If the source is not local , you need to mention remote soruce as yes. 