- name: Demo on using shell module 
  hosts: dev 
  tasks: 
    - name: Running a shell command id
      ansible.builtin.shell: id
      register: OUT1

    - name: Printing the out1 variable 
      ansible.builtin.debug: 
        msg: "{{OUT1.stdout}}"
    
    - name: Running a shell command uptime
      ansible.builtin.shell: uptime
      register: OUT2

    - name: Printing the out2 variable 
      ansible.builtin.debug: 
        msg: "{{OUT2.stdout}}"

        