- name: Demo on conditions 
  hosts: all  
  vars:   
    action: true
    # foo: fantastic
  tasks: 
    - name: Run this when action is true
      ansible.builtin.debug: 
        msg: Action is true  
      when: action
    
    - name: Run this when ansible distribution is Centos 
      ansible.builtin.debug: 
        msg: I am Centos  
      when: ansible_distribution == "CentOS"  
    
    - name: Run this when ansible distribution is Ubuntu 
      ansible.builtin.debug: 
        msg: I am Ubuntu  
      when: ansible_distribution == "Ubuntu"  

    - name: Run the command if "foo" is defined
      ansible.builtin.debug: 
        msg: "I've got foo and am not afraid to use it!"
      when: foo is defined 

    - name: Run the command if "foo" is undefined
      ansible.builtin.fail: 
        msg: I am foo and why am I undefined
      when: foo is undefined 

