- name: Demo on conditions 
  hosts: all  
  vars:   
    action: false
    # foo: fantastic
  tasks: 
    - name: Run this when action is true
      ansible.builtin.debug: 
        msg: Action is true  
      when: action
    
    - name: Run this when ansible distribution is centos 
      ansible.builtin.debug: 
        msg: I am centos  
      when: ansible_distribution = "CentOS"  

    - name: Run the command if "foo" is defined
      ansible.builtin.debug: 
        msg: "I've got foo and am not afraid to use it!"
      when: foo is defined 

    - name: Run the command if "foo" is undefined
      ansible.builtin.debug: 
        msg: I am foo and why am I undefined
      when: foo is undefined 

