- name: Demo on privilege escalation
  hosts: all 
  become: yes 
  tasks: 
    - name: Running a shell command as root user (become:yes)
      ansible.builtin.shell: id
      register: OUT

    - name: Printing the out variable 
      ansible.builtin.debug: 
        msg: "{{OUT.stdout}}" 

    - name: Running a shell commands as centos user 
      ansible.builtin.shell: id
      register: OUT
      become_user: centos 

    - name: Printing the out variable as centos user 
      ansible.builtin.debug: 
        msg: "{{OUT.stdout}}"
      become_user: centos 